package flags

var (
	GCPProjectID    = FlagSet.String("gcp-project-id", "", "GCP project ID")
	GCPSubscription = FlagSet.String("gcp-pubsub-subscription", "", "GCP Pub/Sub subscription name")

	GCPFirestoreRetrieveCollection      = FlagSet.String("gcp-firestore-retrieve-collection", "", "GCP Firestore retrieve collection")
	GCPFirestoreRetrieveDocument        = FlagSet.String("gcp-firestore-retrieve-document", "", "GCP Firestore retrieve document")
	GCPFirestoreRetrieveQueryPath       = FlagSet.String("gcp-firestore-retrieve-query-path", "", "GCP Firestore retrieve query path")
	GCPFirestoreRetrieveQueryOp         = FlagSet.String("gcp-firestore-retrieve-query-op", "", "GCP Firestore retrieve query op")
	GCPFirestoreRetrieveQueryValue      = FlagSet.String("gcp-firestore-retrieve-query-value", "", "GCP Firestore retrieve query value")
	GCPFirestoreRetrieveDocumentJSONKey = FlagSet.String("gcp-firestore-retrieve-document-json-key", "", "GCP Firestore retrieve document JSON key")
	GCPFirestoreRetrieveQueryOrderBy    = FlagSet.String("gcp-firestore-retrieve-query-order-by", "", "GCP Firestore retrieve query order by key")
	GCPFirestoreRetrieveQueryOrder      = FlagSet.String("gcp-firestore-retrieve-query-order", "", "GCP Firestore retrieve query order. Valid values: asc, desc")
	GCPFirestoreClearOp                 = FlagSet.String("gcp-firestore-clear-op", "", "GCP Firestore clear op. Possible values: 'mv', 'rm', 'update'")
	GCPFirestoreClearUpdate             = FlagSet.String("gcp-firestore-clear-update", "", "GCP Firestore clear update object. Will be merged with document before update or move.")
	GCPFirestoreClearCollection         = FlagSet.String("gcp-firestore-clear-collection", "", "GCP Firestore clear collection")
	GCPFirestoreFailOp                  = FlagSet.String("gcp-firestore-fail-op", "", "GCP Firestore fail op. Possible values: 'mv', 'rm', 'update'")
	GCPFirestoreFailUpdate              = FlagSet.String("gcp-firestore-fail-update", "", "GCP Firestore fail update object. Will be merged with document before update or move.")
	GCPFirestoreFailCollection          = FlagSet.String("gcp-firestore-fail-collection", "", "GCP Firestore fail collection")

	GCPGCSBucket           = FlagSet.String("gcp-gcs-bucket", "", "GCP GCS bucket")
	GCPGCSKey              = FlagSet.String("gcp-gcs-key", "", "GCP GCS key")
	GCPGCSKeyRegex         = FlagSet.String("gcp-gcs-key-regex", "", "GCP GCS key regex")
	GCPGCSKeyPrefix        = FlagSet.String("gcp-gcs-key-prefix", "", "GCP GCS key prefix")
	GCPGCSClearOp          = FlagSet.String("gcp-gcs-clear-op", "", "GCP GCS clear operation. Valid values: mv, rm")
	GCPGCSFailOp           = FlagSet.String("gcp-gcs-fail-op", "", "GCP GCS fail operation. Valid values: mv, rm")
	GCPGCSClearBucket      = FlagSet.String("gcp-gcs-clear-bucket", "", "GCP GCS clear bucket, if clear op is mv")
	GCPGCSClearKey         = FlagSet.String("gcp-gcs-clear-key", "", "GCP GCS clear key, if clear op is mv. default is origional key name.")
	GCPGCSClearKeyTemplate = FlagSet.String("gcp-gcs-clear-key-template", "", "GCP GCS clear key template, if clear op is mv.")
	GCPGCSFailBucket       = FlagSet.String("gcp-gcs-fail-bucket", "", "GCP GCS fail bucket, if fail op is mv")
	GCPGCSFailKey          = FlagSet.String("gcp-gcs-fail-key", "", "GCP GCS fail key, if fail op is mv. default is original key name.")
	GCPGCSFailKeyTemplate  = FlagSet.String("gcp-gcs-fail-key-template", "", "GCP GCS fail key template, if fail op is mv.")

	GCPBQRetrieveField = FlagSet.String("gcp-bq-retrieve-field", "", "GCP BigQuery retrieve field")
	GCPBQRetrieveQuery = FlagSet.String("gcp-bq-retrieve-query", "", "GCP BQ retrieve query")
	GCPBQClearQuery    = FlagSet.String("gcp-bq-clear-query", "", "GCP BQ clear query")
	GCPBQFailQuery     = FlagSet.String("gcp-bq-fail-query", "", "GCP BQ fail query")
)
